name: geonames
sources:
  - name: allCountries
    url: https://download.geonames.org/export/dump/allCountries.zip
    file: allCountries.txt
    kind: tabular
    separator: "\t"
    attributes:
      original:
        - name: geonameid
          type: integer
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: alternatenames
          type: text
        - name: latitude
          type: real
        - name: longitude
          type: real
        - name: feature_class
          type: text
        - name: feature_code
          type: text
        - name: country_code
          type: text
          index: true
        - name: cc2
          type: text
        - name: admin1_code
          type: text
        - name: admin2_code
          type: text
        - name: admin3_code
          type: text
        - name: admin4_code
          type: text
        - name: population
          type: integer
        - name: elevation
          type: integer
        - name: dem
          type: integer
        - name: timezone
          type: text
        - name: modification_date
          type: text
      derived:
        - name: geometry
          type: geometry
          expression: "'POINT(' || longitude || ' ' || latitude || ')'"
          index: true
          srid: 4326
        - name: feature_code_full
          type: text
          expression: "feature_class || '.' || feature_code"
          index: true
        - name: admin1_code_full
          type: text
          expression: "country_code || '.' || admin1_code"
          index: true
        - name: admin2_code_full
          type: text
          expression: "country_code || '.' || admin1_code || '.' || admin2_code"
          index: true
        - name: name_no_parens
          type: text
          expression: "CASE WHEN instr(name, '(') > 0 THEN trim(substr(name, 1, instr(name, '(') - 1)) ELSE name END"
        - name: asciiname_no_parens
          type: text
          expression: "CASE WHEN instr(asciiname, '(') > 0 THEN trim(substr(asciiname, 1, instr(asciiname, '(') - 1)) ELSE asciiname END"
    view:
      select:
        - column: allCountries.geonameid
        - column: allCountries.name
        - column: allCountries.name_no_parens
        - column: allCountries.asciiname
        - column: allCountries.asciiname_no_parens
        - column: allCountries.alternatenames
        - column: allCountries.latitude
        - column: allCountries.longitude
        - column: allCountries.feature_class
        - column: allCountries.feature_code
        - column: featureCodes.name
          alias: feature_name
        - column: allCountries.country_code
        - column: countryInfo.Country
          alias: country_name
        - column: allCountries.cc2
        - column: allCountries.admin1_code
        - column: admin1CodesASCII.name
          alias: admin1_name
        - column: allCountries.admin2_code
        - column: admin2Codes.name
          alias: admin2_name
        - column: allCountries.admin3_code
        - column: allCountries.admin4_code
        - column: allCountries.population
        - column: allCountries.elevation
        - column: allCountries.dem
        - column: allCountries.timezone
        - column: allCountries.modification_date
        - column: allCountries.geometry
      join:
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: allCountries.country_code
            right:
              column: countryInfo.ISO
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: allCountries.admin1_code_full
            right:
              column: admin1CodesASCII.code
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: allCountries.admin2_code_full
            right:
              column: admin2Codes.code
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: allCountries.feature_code_full
            right:
              column: featureCodes.code
    features:
      identifier:
        - column: allCountries.geonameid
      names:
        - column: allCountries.name
        - column: allCountries.name_no_parens
        - column: allCountries.asciiname
        - column: allCountries.asciiname_no_parens
        - column: allCountries.alternatenames
          separator: ","

  - name: admin1CodesASCII
    url: https://download.geonames.org/export/dump/admin1CodesASCII.txt
    file: admin1CodesASCII.txt
    kind: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: geonameid
          type: integer

  - name: admin2Codes
    url: https://download.geonames.org/export/dump/admin2Codes.txt
    file: admin2Codes.txt
    kind: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: geonameid
          type: integer

  - name: countryInfo
    url: https://download.geonames.org/export/dump/countryInfo.txt
    file: countryInfo.txt
    kind: tabular
    separator: "\t"
    skiprows: 50
    attributes:
      original:
        - name: ISO
          type: text
          index: true
        - name: ISO3
          type: text
        - name: ISO_Numeric
          type: integer
        - name: fips
          type: text
        - name: Country
          type: text
        - name: Capital
          type: text
        - name: Area
          type: real
        - name: Population
          type: integer
        - name: Continent
          type: text
        - name: tld
          type: text
        - name: CurrencyCode
          type: text
        - name: CurrencyName
          type: text
        - name: Phone
          type: text
        - name: PostalCodeFormat
          type: text
        - name: PostalCodeRegex
          type: text
        - name: Languages
          type: text
        - name: geonameid
          type: integer
        - name: neighbours
          type: text
        - name: EquivalentFipsCode
          type: text

  - name: featureCodes
    url: https://download.geonames.org/export/dump/featureCodes_en.txt
    file: featureCodes_en.txt
    kind: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: description
          type: text