name: geonames-cities
sources:
  - name: cities500
    url: https://download.geonames.org/export/dump/cities500.zip
    file: cities500.txt
    kind: tabular
    separator: "\t"
    attributes:
      original:
        - name: geonameid
          type: integer
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: alternatenames
          type: text
        - name: latitude
          type: real
        - name: longitude
          type: real
        - name: feature_class
          type: text
        - name: feature_code
          type: text
        - name: country_code
          type: text
          index: true
        - name: cc2
          type: text
        - name: admin1_code
          type: text
        - name: admin2_code
          type: text
        - name: admin3_code
          type: text
        - name: admin4_code
          type: text
        - name: population
          type: integer
        - name: elevation
          type: integer
        - name: dem
          type: integer
        - name: timezone
          type: text
        - name: modification_date
          type: text
      derived:
        - name: geometry
          type: geometry
          expression: "'POINT(' || longitude || ' ' || latitude || ')'"
          index: true
          srid: 4326
        - name: feature_code_full
          type: text
          expression: "feature_class || '.' || feature_code"
          index: true
        - name: admin1_code_full
          type: text
          expression: "country_code || '.' || admin1_code"
          index: true
        - name: admin2_code_full
          type: text
          expression: "country_code || '.' || admin1_code || '.' || admin2_code"
          index: true
        - name: name_no_parens
          type: text
          expression: "CASE WHEN instr(name, '(') > 0 THEN trim(substr(name, 1, instr(name, '(') - 1)) ELSE name END"
        - name: asciiname_no_parens
          type: text
          expression: "CASE WHEN instr(asciiname, '(') > 0 THEN trim(substr(asciiname, 1, instr(asciiname, '(') - 1)) ELSE asciiname END"
    view:
      select:
        - column: cities500.geonameid
        - column: cities500.name
        - column: cities500.name_no_parens
        - column: cities500.asciiname
        - column: cities500.asciiname_no_parens
        - column: cities500.alternatenames
        - column: cities500.latitude
        - column: cities500.longitude
        - column: cities500.feature_class
        - column: cities500.feature_code
        - column: featureCodes.name
          alias: feature_name
        - column: cities500.country_code
        - column: countryInfo.Country
          alias: country_name
        - column: cities500.cc2
        - column: cities500.admin1_code
        - column: admin1CodesASCII.name
          alias: admin1_name
        - column: cities500.admin2_code
        - column: admin2Codes.name
          alias: admin2_name
        - column: cities500.admin3_code
        - column: cities500.admin4_code
        - column: cities500.population
        - column: cities500.elevation
        - column: cities500.dem
        - column: cities500.timezone
        - column: cities500.modification_date
        - column: cities500.geometry
      join:
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: cities500.country_code
            right:
              column: countryInfo.ISO
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: cities500.admin1_code_full
            right:
              column: admin1CodesASCII.code
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: cities500.admin2_code_full
            right:
              column: admin2Codes.code
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: cities500.feature_code_full
            right:
              column: featureCodes.code
    features:
      identifier:
        - column: cities500.geonameid
      names:
        - column: cities500.name
        - column: cities500.name_no_parens
        - column: cities500.asciiname
        - column: cities500.asciiname_no_parens
        - column: cities500.alternatenames
          separator: ","

  - name: countryInfo
    url: https://download.geonames.org/export/dump/countryInfo.txt
    file: countryInfo.txt
    kind: tabular
    separator: "\t"
    skiprows: 50
    attributes:
      original:
        - name: ISO
          type: text
          index: true
        - name: ISO3
          type: text
        - name: ISO_Numeric
          type: integer
        - name: fips
          type: text
        - name: Country
          type: text
        - name: Capital
          type: text
        - name: Area
          type: real
        - name: Population
          type: integer
        - name: Continent
          type: text
        - name: tld
          type: text
        - name: CurrencyCode
          type: text
        - name: CurrencyName
          type: text
        - name: Phone
          type: text
        - name: PostalCodeFormat
          type: text
        - name: PostalCodeRegex
          type: text
        - name: Languages
          type: text
        - name: geonameid
          type: integer
        - name: neighbours
          type: text
        - name: EquivalentFipsCode
          type: text
      derived:
        - name: name_no_parens
          type: text
          expression: "CASE WHEN instr(Country, '(') > 0 THEN trim(substr(Country, 1, instr(Country, '(') - 1)) ELSE Country END"
        - name: asciiname
          type: text
          expression: "NULL"
        - name: asciiname_no_parens
          type: text
          expression: "NULL"
        - name: alternatenames
          type: text
          expression: "NULL"
        - name: latitude
          type: real
          expression: "NULL"
        - name: longitude
          type: real
          expression: "NULL"
        - name: feature_class
          type: text
          expression: "NULL"
        - name: feature_code
          type: text
          expression: "NULL"
        - name: feature_name
          type: text
          expression: "NULL"
        - name: cc2
          type: text
          expression: "NULL"
        - name: admin1_code
          type: text
          expression: "NULL"
        - name: admin1_name
          type: text
          expression: "NULL"
        - name: admin2_code
          type: text
          expression: "NULL"
        - name: admin2_name
          type: text
          expression: "NULL"
        - name: admin3_code
          type: text
          expression: "NULL"
        - name: admin4_code
          type: text
          expression: "NULL"
        - name: elevation
          type: integer
          expression: "NULL"
        - name: dem
          type: integer
          expression: "NULL"
        - name: timezone
          type: text
          expression: "NULL"
        - name: modification_date
          type: text
          expression: "NULL"
        - name: geometry
          type: geometry
          expression: "NULL"
          srid: 4326
    view:
      select:
        - column: countryInfo.geonameid
        - column: countryInfo.Country
          alias: name
        - column: countryInfo.name_no_parens
        - column: countryInfo.asciiname
        - column: countryInfo.asciiname_no_parens
        - column: countryInfo.alternatenames
        - column: countryInfo.latitude
        - column: countryInfo.longitude
        - column: countryInfo.feature_class
        - column: countryInfo.feature_code
        - column: countryInfo.feature_name
        - column: countryInfo.ISO
          alias: country_code
        - column: countryInfo.Country
          alias: country_name
        - column: countryInfo.cc2
        - column: countryInfo.admin1_code
        - column: countryInfo.admin1_name
        - column: countryInfo.admin2_code
        - column: countryInfo.admin2_name
        - column: countryInfo.admin3_code
        - column: countryInfo.admin4_code
        - column: countryInfo.Population
          alias: population
        - column: countryInfo.elevation
        - column: countryInfo.dem
        - column: countryInfo.timezone
        - column: countryInfo.modification_date
        - column: countryInfo.geometry
    features:
      identifier:
        - column: countryInfo.geonameid
      names:
        - column: countryInfo.Country

  - name: admin1CodesASCII
    url: https://download.geonames.org/export/dump/admin1CodesASCII.txt
    file: admin1CodesASCII.txt
    kind: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: geonameid
          type: integer
      derived:
        - name: name_no_parens
          type: text
          expression: "CASE WHEN instr(name, '(') > 0 THEN trim(substr(name, 1, instr(name, '(') - 1)) ELSE name END"
        - name: asciiname_no_parens
          type: text
          expression: "CASE WHEN instr(asciiname, '(') > 0 THEN trim(substr(asciiname, 1, instr(asciiname, '(') - 1)) ELSE asciiname END"
        - name: country_code
          type: text
          expression: "CASE WHEN instr(code, '.') > 0 THEN substr(code, 1, instr(code, '.') - 1) ELSE code END"
        - name: admin1_code
          type: text
          expression: "CASE WHEN instr(code, '.') > 0 THEN substr(code, instr(code, '.') + 1) ELSE NULL END"
        - name: alternatenames
          type: text
          expression: "NULL"
        - name: latitude
          type: real
          expression: "NULL"
        - name: longitude
          type: real
          expression: "NULL"
        - name: feature_class
          type: text
          expression: "NULL"
        - name: feature_code
          type: text
          expression: "NULL"
        - name: feature_name
          type: text
          expression: "NULL"
        - name: cc2
          type: text
          expression: "NULL"
        - name: admin2_code
          type: text
          expression: "NULL"
        - name: admin2_name
          type: text
          expression: "NULL"
        - name: admin3_code
          type: text
          expression: "NULL"
        - name: admin4_code
          type: text
          expression: "NULL"
        - name: population
          type: integer
          expression: "NULL"
        - name: elevation
          type: integer
          expression: "NULL"
        - name: dem
          type: integer
          expression: "NULL"
        - name: timezone
          type: text
          expression: "NULL"
        - name: modification_date
          type: text
          expression: "NULL"
        - name: geometry
          type: geometry
          expression: "NULL"
          srid: 4326
    view:
      select:
        - column: admin1CodesASCII.geonameid
        - column: admin1CodesASCII.name
        - column: admin1CodesASCII.name_no_parens
        - column: admin1CodesASCII.asciiname
        - column: admin1CodesASCII.asciiname_no_parens
        - column: admin1CodesASCII.alternatenames
        - column: admin1CodesASCII.latitude
        - column: admin1CodesASCII.longitude
        - column: admin1CodesASCII.feature_class
        - column: admin1CodesASCII.feature_code
        - column: admin1CodesASCII.feature_name
        - column: admin1CodesASCII.country_code
        - column: countryInfo.Country
          alias: country_name
        - column: admin1CodesASCII.cc2
        - column: admin1CodesASCII.admin1_code
        - column: admin1CodesASCII.name
          alias: admin1_name
        - column: admin1CodesASCII.admin2_code
        - column: admin1CodesASCII.admin2_name
        - column: admin1CodesASCII.admin3_code
        - column: admin1CodesASCII.admin4_code
        - column: admin1CodesASCII.population
        - column: admin1CodesASCII.elevation
        - column: admin1CodesASCII.dem
        - column: admin1CodesASCII.timezone
        - column: admin1CodesASCII.modification_date
        - column: admin1CodesASCII.geometry
      join:
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: admin1CodesASCII.country_code
            right:
              column: countryInfo.ISO
    features:
      identifier:
        - column: admin1CodesASCII.geonameid
      names:
        - column: admin1CodesASCII.name
        - column: admin1CodesASCII.asciiname

  - name: admin2Codes
    url: https://download.geonames.org/export/dump/admin2Codes.txt
    file: admin2Codes.txt
    kind: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: geonameid
          type: integer
      derived:
        - name: name_no_parens
          type: text
          expression: "CASE WHEN instr(name, '(') > 0 THEN trim(substr(name, 1, instr(name, '(') - 1)) ELSE name END"
        - name: asciiname_no_parens
          type: text
          expression: "CASE WHEN instr(asciiname, '(') > 0 THEN trim(substr(asciiname, 1, instr(asciiname, '(') - 1)) ELSE asciiname END"
        - name: country_code
          type: text
          expression: "CASE WHEN instr(code, '.') > 0 THEN substr(code, 1, instr(code, '.') - 1) ELSE code END"
        - name: admin1_code
          type: text
          expression: "CASE WHEN instr(code, '.') > 0 AND instr(substr(code, instr(code, '.') + 1), '.') > 0 THEN substr(substr(code, instr(code, '.') + 1), 1, instr(substr(code, instr(code, '.') + 1), '.') - 1) ELSE NULL END"
        - name: admin2_code
          type: text
          expression: "CASE WHEN instr(code, '.') > 0 AND instr(substr(code, instr(code, '.') + 1), '.') > 0 THEN substr(substr(code, instr(code, '.') + 1), instr(substr(code, instr(code, '.') + 1), '.') + 1) ELSE NULL END"
        - name: admin1_code_full
          type: text
          expression: "country_code || '.' || admin1_code"
        - name: alternatenames
          type: text
          expression: "NULL"
        - name: latitude
          type: real
          expression: "NULL"
        - name: longitude
          type: real
          expression: "NULL"
        - name: feature_class
          type: text
          expression: "NULL"
        - name: feature_code
          type: text
          expression: "NULL"
        - name: feature_name
          type: text
          expression: "NULL"
        - name: cc2
          type: text
          expression: "NULL"
        - name: admin3_code
          type: text
          expression: "NULL"
        - name: admin4_code
          type: text
          expression: "NULL"
        - name: population
          type: integer
          expression: "NULL"
        - name: elevation
          type: integer
          expression: "NULL"
        - name: dem
          type: integer
          expression: "NULL"
        - name: timezone
          type: text
          expression: "NULL"
        - name: modification_date
          type: text
          expression: "NULL"
        - name: geometry
          type: geometry
          expression: "NULL"
          srid: 4326
    view:
      select:
        - column: admin2Codes.geonameid
        - column: admin2Codes.name
        - column: admin2Codes.name_no_parens
        - column: admin2Codes.asciiname
        - column: admin2Codes.asciiname_no_parens
        - column: admin2Codes.alternatenames
        - column: admin2Codes.latitude
        - column: admin2Codes.longitude
        - column: admin2Codes.feature_class
        - column: admin2Codes.feature_code
        - column: admin2Codes.feature_name
        - column: admin2Codes.country_code
        - column: countryInfo.Country
          alias: country_name
        - column: admin2Codes.cc2
        - column: admin2Codes.admin1_code
        - column: admin1CodesASCII.name
          alias: admin1_name
        - column: admin2Codes.admin2_code
        - column: admin2Codes.name
          alias: admin2_name
        - column: admin2Codes.admin3_code
        - column: admin2Codes.admin4_code
        - column: admin2Codes.population
        - column: admin2Codes.elevation
        - column: admin2Codes.dem
        - column: admin2Codes.timezone
        - column: admin2Codes.modification_date
        - column: admin2Codes.geometry
      join:
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: admin2Codes.country_code
            right:
              column: countryInfo.ISO
        - method: left join
          condition:
            type: attribute
            predicate: equals
            left:
              column: admin2Codes.admin1_code_full
            right:
              column: admin1CodesASCII.code
    features:
      identifier:
        - column: admin2Codes.geonameid
      names:
        - column: admin2Codes.name
        - column: admin2Codes.asciiname

  - name: featureCodes
    url: https://download.geonames.org/export/dump/featureCodes_en.txt
    file: featureCodes_en.txt
    kind: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: description
          type: text
