name: geonames
sources:
  - name: allCountries
    url: https://download.geonames.org/export/dump/allCountries.zip
    file: allCountries.txt
    type: tabular
    separator: "\t"
    attributes:
      original:
        - name: geonameid
          type: integer
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: alternatenames
          type: text
        - name: latitude
          type: real
        - name: longitude
          type: real
        - name: feature_class
          type: text
        - name: feature_code
          type: text
        - name: country_code
          type: text
          index: true
        - name: cc2
          type: text
        - name: admin1_code
          type: text
        - name: admin2_code
          type: text
        - name: admin3_code
          type: text
        - name: admin4_code
          type: text
        - name: population
          type: integer
        - name: elevation
          type: integer
        - name: dem
          type: integer
        - name: timezone
          type: text
        - name: modification_date
          type: text
      derived:
        - name: geometry
          type: geometry
          expression: "'POINT(' || longitude || ' ' || latitude || ')'"
          index: true
          srid: 4326
        - name: feature_code_full
          type: text
          expression: "feature_class || '.' || feature_code"
          index: true
        - name: admin1_code_full
          type: text
          expression: "country_code || '.' || admin1_code"
          index: true
        - name: admin2_code_full
          type: text
          expression: "country_code || '.' || admin1_code || '.' || admin2_code"
          index: true
        - name: name_no_parens
          type: text
          expression: "CASE WHEN instr(name, '(') > 0 THEN trim(substr(name, 1, instr(name, '(') - 1)) ELSE name END"
        - name: asciiname_no_parens
          type: text
          expression: "CASE WHEN instr(asciiname, '(') > 0 THEN trim(substr(asciiname, 1, instr(asciiname, '(') - 1)) ELSE asciiname END"
    view:
      select:
        - source: allCountries
          column: geonameid
        - source: allCountries
          column: name
        - source: allCountries
          column: name_no_parens
        - source: allCountries
          column: asciiname
        - source: allCountries
          column: asciiname_no_parens
        - source: allCountries
          column: alternatenames
        - source: allCountries
          column: latitude
        - source: allCountries
          column: longitude
        - source: allCountries
          column: feature_class
        - source: allCountries
          column: feature_code
        - source: featureCodes
          column: name
          alias: feature_name
        - source: allCountries
          column: country_code
        - source: countryInfo
          column: Country
          alias: country_name
        - source: allCountries
          column: cc2
        - source: allCountries
          column: admin1_code
        - source: admin1CodesASCII
          column: name
          alias: admin1_name
        - source: allCountries
          column: admin2_code
        - source: admin2Codes
          column: name
          alias: admin2_name
        - source: allCountries
          column: admin3_code
        - source: allCountries
          column: admin4_code
        - source: allCountries
          column: population
        - source: allCountries
          column: elevation
        - source: allCountries
          column: dem
        - source: allCountries
          column: timezone
        - source: allCountries
          column: modification_date
        - source: allCountries
          column: geometry
      join:
        - method: left join
          source: countryInfo
          condition:
            type: attribute
            predicate: equals
            left: allCountries.country_code
            right: countryInfo.ISO
        - method: left join
          source: admin1CodesASCII
          condition:
            type: attribute
            predicate: equals
            left: allCountries.admin1_code_full
            right: admin1CodesASCII.code
        - method: left join
          source: admin2Codes
          condition:
            type: attribute
            predicate: equals
            left: allCountries.admin2_code_full
            right: admin2Codes.code
        - method: left join
          source: featureCodes
          condition:
            type: attribute
            predicate: equals
            left: allCountries.feature_code_full
            right: featureCodes.code
    features:
      identifier:
        - column: geonameid
      names:
        - column: name
        - column: name_no_parens
        - column: asciiname
        - column: asciiname_no_parens
        - column: alternatenames
          separator: ","

  - name: admin1CodesASCII
    url: https://download.geonames.org/export/dump/admin1CodesASCII.txt
    file: admin1CodesASCII.txt
    type: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: geonameid
          type: integer

  - name: admin2Codes
    url: https://download.geonames.org/export/dump/admin2Codes.txt
    file: admin2Codes.txt
    type: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: asciiname
          type: text
        - name: geonameid
          type: integer

  - name: countryInfo
    url: https://download.geonames.org/export/dump/countryInfo.txt
    file: countryInfo.txt
    type: tabular
    separator: "\t"
    skiprows: 50
    attributes:
      original:
        - name: ISO
          type: text
          index: true
        - name: ISO3
          type: text
        - name: ISO_Numeric
          type: integer
        - name: fips
          type: text
        - name: Country
          type: text
        - name: Capital
          type: text
        - name: Area
          type: real
        - name: Population
          type: integer
        - name: Continent
          type: text
        - name: tld
          type: text
        - name: CurrencyCode
          type: text
        - name: CurrencyName
          type: text
        - name: Phone
          type: text
        - name: PostalCodeFormat
          type: text
        - name: PostalCodeRegex
          type: text
        - name: Languages
          type: text
        - name: geonameid
          type: integer
        - name: neighbours
          type: text
        - name: EquivalentFipsCode
          type: text

  - name: featureCodes
    url: https://download.geonames.org/export/dump/featureCodes_en.txt
    file: featureCodes_en.txt
    type: tabular
    separator: "\t"
    attributes:
      original:
        - name: code
          type: text
          index: true
        - name: name
          type: text
        - name: description
          type: text