from geoparser.db.crud.document import DocumentRepository
from geoparser.db.crud.gazetteer import GazetteerRepository
from geoparser.db.crud.location import LocationRepository
from geoparser.db.crud.project import ProjectRepository
from geoparser.db.crud.recognition_module import RecognitionModuleRepository
from geoparser.db.crud.recognition_object import RecognitionObjectRepository
from geoparser.db.crud.recognition_subject import RecognitionSubjectRepository
from geoparser.db.crud.resolution_module import ResolutionModuleRepository
from geoparser.db.crud.resolution_object import ResolutionObjectRepository
from geoparser.db.crud.resolution_subject import ResolutionSubjectRepository
from geoparser.db.crud.toponym import ToponymRepository
