name: geonames
sources:
  - name: allCountries
    type: tabular
    url: https://download.geonames.org/export/dump/allCountries.zip
    file: allCountries.txt
    separator: "\t"
    attributes:
      - name: geonameid
        type: INTEGER
        primary: true
      - name: name
        type: TEXT
      - name: asciiname
        type: TEXT
      - name: alternatenames
        type: TEXT
      - name: latitude
        type: REAL
      - name: longitude
        type: REAL
      - name: feature_class
        type: TEXT
      - name: feature_code
        type: TEXT
      - name: country_code
        type: TEXT
      - name: cc2
        type: TEXT
      - name: admin1_code
        type: TEXT
      - name: admin2_code
        type: TEXT
      - name: admin3_code
        type: TEXT
      - name: admin4_code
        type: TEXT
      - name: population
        type: INTEGER
      - name: elevation
        type: INTEGER
      - name: dem
        type: INTEGER
      - name: timezone
        type: TEXT
      - name: modification_date
        type: TEXT
    derivations:
      - name: geometry
        type: TEXT
        expression: "'POINT(' || longitude || ' ' || latitude || ')'"
      - name: feature_code_full
        type: TEXT
        expression: "feature_class || '.' || feature_code"
      - name: admin1_code_full
        type: TEXT
        expression: "country_code || '.' || admin1_code"
      - name: admin2_code_full
        type: TEXT
        expression: "country_code || '.' || admin1_code || '.' || admin2_code"

  - name: admin1CodesASCII
    type: tabular
    url: https://download.geonames.org/export/dump/admin1CodesASCII.txt
    file: admin1CodesASCII.txt
    separator: "\t"
    attributes:
      - name: code
        type: TEXT
        primary: true
      - name: name
        type: TEXT
      - name: asciiname
        type: TEXT
      - name: geonameid
        type: INTEGER

  - name: admin2Codes
    type: tabular
    url: https://download.geonames.org/export/dump/admin2Codes.txt
    file: admin2Codes.txt
    separator: "\t"
    attributes:
      - name: code
        type: TEXT
        primary: true
      - name: name
        type: TEXT
      - name: asciiname
        type: TEXT
      - name: geonameid
        type: INTEGER

  - name: countryInfo
    type: tabular
    url: https://download.geonames.org/export/dump/countryInfo.txt
    file: countryInfo.txt
    separator: "\t"
    skiprows: 50
    attributes:
      - name: ISO
        type: TEXT
        primary: true
      - name: ISO3
        type: TEXT
      - name: ISO_Numeric
        type: INTEGER
      - name: fips
        type: TEXT
      - name: Country
        type: TEXT
      - name: Capital
        type: TEXT
      - name: Area
        type: REAL
      - name: Population
        type: INTEGER
      - name: Continent
        type: TEXT
      - name: tld
        type: TEXT
      - name: CurrencyCode
        type: TEXT
      - name: CurrencyName
        type: TEXT
      - name: Phone
        type: TEXT
      - name: PostalCodeFormat
        type: TEXT
      - name: PostalCodeRegex
        type: TEXT
      - name: Languages
        type: TEXT
      - name: geonameid
        type: INTEGER
      - name: neighbours
        type: TEXT
      - name: EquivalentFipsCode
        type: TEXT

  - name: featureCodes
    type: tabular
    url: https://download.geonames.org/export/dump/featureCodes_en.txt
    file: featureCodes_en.txt
    separator: "\t"
    attributes:
      - name: code
        type: TEXT
        primary: true
      - name: name
        type: TEXT
      - name: description
        type: TEXT

  - name: alternateNames
    type: tabular
    url: https://download.geonames.org/export/dump/alternateNames.zip
    file: alternateNames.txt
    separator: "\t"
    attributes:
      - name: alternateNameId
        type: INTEGER
        primary: true
      - name: geonameid
        type: INTEGER
      - name: isolanguage
        type: TEXT
      - name: alternate_name
        type: TEXT
      - name: isPreferredName
        type: INTEGER
      - name: isShortName
        type: INTEGER
      - name: isColloquial
        type: INTEGER
      - name: isHistoric
        type: INTEGER
      - name: xfrom
        type: TEXT
      - name: xto
        type: TEXT

views:
  - name: allCountriesEnriched
    statement:
      select:
        - allCountries.*
        - "countryInfo.Country AS country_name"
        - "countryInfo.Continent AS continent"
        - "admin1.name AS admin1_name"
        - "admin2.name AS admin2_name"
        - "features.name AS feature_name"
        - "features.description AS feature_description"
      from:
        - allCountries
      join:
        - "LEFT JOIN countryInfo ON allCountries.country_code = countryInfo.ISO"
        - "LEFT JOIN admin1CodesASCII AS admin1 ON allCountries.admin1_code_full = admin1.code"
        - "LEFT JOIN admin2Codes AS admin2 ON allCountries.admin2_code_full = admin2.code"
        - "LEFT JOIN featureCodes AS features ON allCountries.feature_code_full = features.code" 