name: geonames
sources:
  - id: allCountries
    type: tabular
    url: https://download.geonames.org/export/dump/allCountries.zip
    file: allCountries.txt
    separator: "\t"
    skiprows: 0
    columns:
      - name: geonameid
      - name: name
      - name: asciiname
      - name: alternatenames
      - name: latitude
      - name: longitude
      - name: feature_class
      - name: feature_code
      - name: country_code
      - name: cc2
      - name: admin1_code
      - name: admin2_code
      - name: admin3_code
      - name: admin4_code
      - name: population
      - name: elevation
      - name: dem
      - name: timezone
      - name: modification_date
    geometry:
      x: longitude
      y: latitude
      crs: EPSG:4326

  - id: admin1CodesASCII
    type: tabular
    url: https://download.geonames.org/export/dump/admin1CodesASCII.txt
    file: admin1CodesASCII.txt
    separator: "\t"
    skiprows: 0
    columns:
      - name: code
      - name: name
      - name: asciiname
      - name: geonameid

  - id: admin2Codes
    type: tabular
    url: https://download.geonames.org/export/dump/admin2Codes.txt
    file: admin2Codes.txt
    separator: "\t"
    skiprows: 0
    columns:
      - name: code
      - name: name
      - name: asciiname
      - name: geonameid

  - id: countryInfo
    type: tabular
    url: https://download.geonames.org/export/dump/countryInfo.txt
    file: countryInfo.txt
    separator: "\t"
    skiprows: 50
    columns:
      - name: ISO
      - name: ISO3
      - name: ISO_Numeric
      - name: fips
      - name: Country
      - name: Capital
      - name: Area
      - name: Population
      - name: Continent
      - name: tld
      - name: CurrencyCode
      - name: CurrencyName
      - name: Phone
      - name: PostalCodeFormat
      - name: PostalCodeRegex
      - name: Languages
      - name: geonameid
      - name: neighbours
      - name: EquivalentFipsCode

  - id: featureCodes_en
    type: tabular
    url: https://download.geonames.org/export/dump/featureCodes_en.txt
    file: featureCodes_en.txt
    separator: "\t"
    skiprows: 0
    columns:
      - name: code
      - name: name
      - name: description

  - id: alternateNames
    type: tabular
    url: https://download.geonames.org/export/dump/alternateNames.zip
    file: alternateNames.txt
    separator: "\t"
    skiprows: 0
    columns:
      - name: alternateNameId
      - name: geonameid
      - name: isolanguage
      - name: alternate_name
      - name: isPreferredName
      - name: isShortName
      - name: isColloquial
      - name: isHistoric
      - name: from
      - name: to 