name: geonames
sources:
  - name: allCountries
    type: tabular
    url: https://download.geonames.org/export/dump/allCountries.zip
    file: allCountries.txt
    separator: "\t"
    attributes:
      - name: geonameid
        type: INTEGER
        primary: true
      - name: name
        type: TEXT
      - name: asciiname
        type: TEXT
      - name: alternatenames
        type: TEXT
      - name: latitude
        type: REAL
      - name: longitude
        type: REAL
      - name: feature_class
        type: TEXT
      - name: feature_code
        type: TEXT
      - name: country_code
        type: TEXT
        index: true
      - name: cc2
        type: TEXT
      - name: admin1_code
        type: TEXT
      - name: admin2_code
        type: TEXT
      - name: admin3_code
        type: TEXT
      - name: admin4_code
        type: TEXT
      - name: population
        type: INTEGER
      - name: elevation
        type: INTEGER
      - name: dem
        type: INTEGER
      - name: timezone
        type: TEXT
      - name: modification_date
        type: TEXT
    derivations:
      - name: geometry
        type: GEOMETRY
        index: true
        srid: 4326
        expression: "'POINT(' || longitude || ' ' || latitude || ')'"
      - name: feature_code_full
        type: TEXT
        index: true
        expression: "feature_class || '.' || feature_code"
      - name: admin1_code_full
        type: TEXT
        index: true
        expression: "country_code || '.' || admin1_code"
      - name: admin2_code_full
        type: TEXT
        index: true
        expression: "country_code || '.' || admin1_code || '.' || admin2_code"
      - name: name_no_parens
        type: TEXT
        expression: "CASE WHEN instr(name, '(') > 0 THEN trim(substr(name, 1, instr(name, '(') - 1)) ELSE name END"
      - name: asciiname_no_parens
        type: TEXT
        expression: "CASE WHEN instr(asciiname, '(') > 0 THEN trim(substr(asciiname, 1, instr(asciiname, '(') - 1)) ELSE asciiname END"

  - name: admin1CodesASCII
    type: tabular
    url: https://download.geonames.org/export/dump/admin1CodesASCII.txt
    file: admin1CodesASCII.txt
    separator: "\t"
    attributes:
      - name: code
        type: TEXT
        primary: true
      - name: name
        type: TEXT
      - name: asciiname
        type: TEXT
      - name: geonameid
        type: INTEGER

  - name: admin2Codes
    type: tabular
    url: https://download.geonames.org/export/dump/admin2Codes.txt
    file: admin2Codes.txt
    separator: "\t"
    attributes:
      - name: code
        type: TEXT
        primary: true
      - name: name
        type: TEXT
      - name: asciiname
        type: TEXT
      - name: geonameid
        type: INTEGER

  - name: countryInfo
    type: tabular
    url: https://download.geonames.org/export/dump/countryInfo.txt
    file: countryInfo.txt
    separator: "\t"
    skiprows: 50
    attributes:
      - name: ISO
        type: TEXT
        primary: true
      - name: ISO3
        type: TEXT
      - name: ISO_Numeric
        type: INTEGER
      - name: fips
        type: TEXT
      - name: Country
        type: TEXT
      - name: Capital
        type: TEXT
      - name: Area
        type: REAL
      - name: Population
        type: INTEGER
      - name: Continent
        type: TEXT
      - name: tld
        type: TEXT
      - name: CurrencyCode
        type: TEXT
      - name: CurrencyName
        type: TEXT
      - name: Phone
        type: TEXT
      - name: PostalCodeFormat
        type: TEXT
      - name: PostalCodeRegex
        type: TEXT
      - name: Languages
        type: TEXT
      - name: geonameid
        type: INTEGER
      - name: neighbours
        type: TEXT
      - name: EquivalentFipsCode
        type: TEXT

  - name: featureCodes
    type: tabular
    url: https://download.geonames.org/export/dump/featureCodes_en.txt
    file: featureCodes_en.txt
    separator: "\t"
    attributes:
      - name: code
        type: TEXT
        primary: true
      - name: name
        type: TEXT
      - name: description
        type: TEXT

views:
  - name: allCountriesEnriched
    statement:
      select:
        - "allCountries.geonameid"
        - "allCountries.name"
        - "allCountries.name_no_parens"
        - "allCountries.asciiname"
        - "allCountries.asciiname_no_parens"
        - "allCountries.alternatenames"
        - "allCountries.latitude"
        - "allCountries.longitude"
        - "allCountries.feature_class"
        - "allCountries.feature_code"
        - "featureCodes.name AS feature_name"
        - "allCountries.country_code"
        - "countryInfo.Country AS country_name"
        - "allCountries.cc2"
        - "allCountries.admin1_code"
        - "admin1CodesASCII.name AS admin1_name"
        - "allCountries.admin2_code"
        - "admin2Codes.name AS admin2_name"
        - "allCountries.admin3_code"
        - "allCountries.admin4_code"
        - "allCountries.population"
        - "allCountries.elevation"
        - "allCountries.dem"
        - "allCountries.timezone"
        - "allCountries.modification_date"
        - "allCountries.geometry"
      from:
        - allCountries
      join:
        - "LEFT JOIN countryInfo ON allCountries.country_code = countryInfo.ISO"
        - "LEFT JOIN admin1CodesASCII ON allCountries.admin1_code_full = admin1CodesASCII.code"
        - "LEFT JOIN admin2Codes ON allCountries.admin2_code_full = admin2Codes.code"
        - "LEFT JOIN featureCodes ON allCountries.feature_code_full = featureCodes.code"

features:
  - table: allCountries
    view: allCountriesEnriched
    identifier_column: geonameid

toponyms:
  - table: allCountries
    view: allCountriesEnriched
    identifier_column: geonameid
    toponym_column: name
  - table: allCountries
    view: allCountriesEnriched
    identifier_column: geonameid
    toponym_column: name_no_parens
  - table: allCountries
    view: allCountriesEnriched
    identifier_column: geonameid
    toponym_column: asciiname
  - table: allCountries
    view: allCountriesEnriched
    identifier_column: geonameid
    toponym_column: asciiname_no_parens
  - table: allCountries
    view: allCountriesEnriched
    identifier_column: geonameid
    toponym_column: alternatenames
    separator: ","