name: swissnames3d
sources:
  - id: swissNAMES3D_PKT
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    file: swissNAMES3D_PKT.shp
    columns:
      - name: UUID
      - name: OBJEKTART
      - name: OBJEKTKLAS
      - name: HOEHE
      - name: GEBAEUDENU
      - name: NAME_UUID
      - name: NAME
      - name: STATUS
      - name: SPRACHCODE
      - name: NAMEN_TYP
      - name: NAMENGRUPP

  - id: swissNAMES3D_LIN
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    file: swissNAMES3D_LIN.shp
    columns:
      - name: UUID
      - name: OBJEKTART
      - name: OBJEKTKLAS
      - name: KUNSTBAUTE
      - name: NAME_UUID
      - name: NAME
      - name: STATUS
      - name: SPRACHCODE
      - name: NAMEN_TYP
      - name: NAMENGRUPP

  - id: swissNAMES3D_PLY
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    file: swissNAMES3D_PLY.shp
    columns:
      - name: UUID
      - name: OBJEKTART
      - name: OBJEKTKLAS
      - name: EINWOHNERK
      - name: NAME_UUID
      - name: NAME
      - name: STATUS
      - name: SPRACHCODE
      - name: NAMEN_TYP
      - name: NAMENGRUPP
      - name: ISCED

  - id: swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    file: swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.shp
    columns:
      - name: UUID
      - name: DATUM_AEND
      - name: DATUM_ERST
      - name: ERSTELL_J
      - name: ERSTELL_M
      - name: GRUND_AEND
      - name: HERKUNFT
      - name: HERKUNFT_J
      - name: HERKUNFT_M
      - name: REVISION_J
      - name: REVISION_M
      - name: REVISION_Q
      - name: OBJEKTART
      - name: BFS_NUMMER
      - name: BEZIRKSNUM
      - name: KANTONSNUM
      - name: NAME
      - name: GEM_FLAECH
      - name: SEE_FLAECH
      - name: ICC
      - name: SHN
      - name: EINWOHNERZ
      - name: HIST_NR

  - id: swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    file: swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.shp
    columns:
      - name: UUID
      - name: DATUM_AEND
      - name: DATUM_ERST
      - name: ERSTELL_J
      - name: ERSTELL_M
      - name: GRUND_AEND
      - name: HERKUNFT
      - name: HERKUNFT_J
      - name: HERKUNFT_M
      - name: REVISION_J
      - name: REVISION_M
      - name: REVISION_Q
      - name: OBJEKTART
      - name: BEZIRKSNUM
      - name: SEE_FLAECH
      - name: BEZIRKSFLA
      - name: NAME
      - name: KANTONSNUM
      - name: ICC
      - name: EINWOHNERZ

  - id: swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    file: swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.shp
    columns:
      - name: UUID
      - name: DATUM_AEND
      - name: DATUM_ERST
      - name: ERSTELL_J
      - name: ERSTELL_M
      - name: GRUND_AEND
      - name: HERKUNFT
      - name: HERKUNFT_J
      - name: HERKUNFT_M
      - name: REVISION_J
      - name: REVISION_M
      - name: REVISION_Q
      - name: OBJEKTART
      - name: KANTONSNUM
      - name: SEE_FLAECH
      - name: KANTONSFLA
      - name: NAME
      - name: ICC
      - name: EINWOHNERZ 