name: swissnames3d
sources:
  - name: swissNAMES3D_PKT
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    file: swissNAMES3D_PKT.shp
    attributes:
      - name: UUID
        type: TEXT
        primary: true
      - name: OBJEKTART
        type: TEXT
      - name: OBJEKTKLAS
        type: TEXT
      - name: HOEHE
        type: REAL
      - name: GEBAEUDENU
        type: INTEGER
      - name: NAME_UUID
        type: TEXT
        primary: true
      - name: NAME
        type: TEXT
      - name: STATUS
        type: TEXT
      - name: SPRACHCODE
        type: TEXT
      - name: NAMEN_TYP
        type: TEXT
      - name: NAMENGRUPP
        type: TEXT
      - name: geometry
        type: GEOMETRY
        index: true
        srid: 2056

  - name: swissNAMES3D_LIN
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    file: swissNAMES3D_LIN.shp
    attributes:
      - name: UUID
        type: TEXT
        primary: true
      - name: OBJEKTART
        type: TEXT
      - name: OBJEKTKLAS
        type: TEXT
      - name: KUNSTBAUTE
        type: TEXT
      - name: NAME_UUID
        type: TEXT
        primary: true
      - name: NAME
        type: TEXT
      - name: STATUS
        type: TEXT
      - name: SPRACHCODE
        type: TEXT
      - name: NAMEN_TYP
        type: TEXT
      - name: NAMENGRUPP
        type: TEXT
      - name: geometry
        type: GEOMETRY
        index: true
        srid: 2056

  - name: swissNAMES3D_PLY
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    file: swissNAMES3D_PLY.shp
    attributes:
      - name: UUID
        type: TEXT
        primary: true
      - name: OBJEKTART
        type: TEXT
      - name: OBJEKTKLAS
        type: TEXT
      - name: EINWOHNERK
        type: INTEGER
      - name: NAME_UUID
        type: TEXT
        primary: true
      - name: NAME
        type: TEXT
      - name: STATUS
        type: TEXT
      - name: SPRACHCODE
        type: TEXT
      - name: NAMEN_TYP
        type: TEXT
      - name: NAMENGRUPP
        type: TEXT
      - name: ISCED
        type: TEXT
      - name: geometry
        type: GEOMETRY
        index: true
        srid: 2056

  - name: swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    file: swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.shp
    attributes:
      - name: UUID
        type: TEXT
        primary: true
      - name: DATUM_AEND
        type: TEXT
      - name: DATUM_ERST
        type: TEXT
      - name: ERSTELL_J
        type: INTEGER
      - name: ERSTELL_M
        type: INTEGER
      - name: GRUND_AEND
        type: TEXT
      - name: HERKUNFT
        type: TEXT
      - name: HERKUNFT_J
        type: INTEGER
      - name: HERKUNFT_M
        type: INTEGER
      - name: REVISION_J
        type: INTEGER
      - name: REVISION_M
        type: INTEGER
      - name: REVISION_Q
        type: INTEGER
      - name: OBJEKTART
        type: TEXT
      - name: BFS_NUMMER
        type: INTEGER
      - name: BEZIRKSNUM
        type: INTEGER
      - name: KANTONSNUM
        type: INTEGER
      - name: NAME
        type: TEXT
      - name: GEM_FLAECH
        type: REAL
      - name: SEE_FLAECH
        type: REAL
      - name: ICC
        type: TEXT
      - name: SHN
        type: TEXT
      - name: EINWOHNERZ
        type: INTEGER
      - name: HIST_NR
        type: INTEGER
      - name: geometry
        type: GEOMETRY
        index: true
        srid: 2056

  - name: swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    file: swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.shp
    attributes:
      - name: UUID
        type: TEXT
        primary: true
      - name: DATUM_AEND
        type: TEXT
      - name: DATUM_ERST
        type: TEXT
      - name: ERSTELL_J
        type: INTEGER
      - name: ERSTELL_M
        type: INTEGER
      - name: GRUND_AEND
        type: TEXT
      - name: HERKUNFT
        type: TEXT
      - name: HERKUNFT_J
        type: INTEGER
      - name: HERKUNFT_M
        type: INTEGER
      - name: REVISION_J
        type: INTEGER
      - name: REVISION_M
        type: INTEGER
      - name: REVISION_Q
        type: INTEGER
      - name: OBJEKTART
        type: TEXT
      - name: BEZIRKSNUM
        type: INTEGER
      - name: SEE_FLAECH
        type: REAL
      - name: BEZIRKSFLA
        type: REAL
      - name: NAME
        type: TEXT
      - name: KANTONSNUM
        type: INTEGER
      - name: ICC
        type: TEXT
      - name: EINWOHNERZ
        type: INTEGER
      - name: geometry
        type: GEOMETRY
        index: true
        srid: 2056

  - name: swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET
    type: spatial
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    file: swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.shp
    attributes:
      - name: UUID
        type: TEXT
        primary: true
      - name: DATUM_AEND
        type: TEXT
      - name: DATUM_ERST
        type: TEXT
      - name: ERSTELL_J
        type: INTEGER
      - name: ERSTELL_M
        type: INTEGER
      - name: GRUND_AEND
        type: TEXT
      - name: HERKUNFT
        type: TEXT
      - name: HERKUNFT_J
        type: INTEGER
      - name: HERKUNFT_M
        type: INTEGER
      - name: REVISION_J
        type: INTEGER
      - name: REVISION_M
        type: INTEGER
      - name: REVISION_Q
        type: INTEGER
      - name: OBJEKTART
        type: TEXT
      - name: KANTONSNUM
        type: INTEGER
      - name: SEE_FLAECH
        type: REAL
      - name: KANTONSFLA
        type: REAL
      - name: NAME
        type: TEXT
      - name: ICC
        type: TEXT
      - name: EINWOHNERZ
        type: INTEGER
      - name: geometry
        type: GEOMETRY
        index: true
        srid: 2056 

views:
  - name: swissNAMES3D_PKT_enriched
    statement:
      select:
        - "swissNAMES3D_PKT.UUID"
        - "swissNAMES3D_PKT.OBJEKTART"
        - "swissNAMES3D_PKT.OBJEKTKLAS"
        - "swissNAMES3D_PKT.HOEHE"
        - "swissNAMES3D_PKT.GEBAEUDENU"
        - "swissNAMES3D_PKT.NAME_UUID"
        - "swissNAMES3D_PKT.NAME"
        - "swissNAMES3D_PKT.STATUS"
        - "swissNAMES3D_PKT.SPRACHCODE"
        - "swissNAMES3D_PKT.NAMEN_TYP"
        - "swissNAMES3D_PKT.NAMENGRUPP"
        - "swissNAMES3D_PKT.geometry"
        - "swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.NAME AS GEMEINDE_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.BFS_NUMMER AS GEMEINDE_BFS_NUMMER"
        - "swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.NAME AS BEZIRK_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.BEZIRKSNUM AS BEZIRKSNUM"
        - "swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.NAME AS KANTON_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.KANTONSNUM AS KANTONSNUM"
      from:
        - swissNAMES3D_PKT
      join:
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET ON ST_Within(swissNAMES3D_PKT.geometry, swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.geometry)"
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET ON swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.BEZIRKSNUM = swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.BEZIRKSNUM"
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET ON swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.KANTONSNUM = swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.KANTONSNUM"

  - name: swissNAMES3D_LIN_enriched
    statement:
      select:
        - "swissNAMES3D_LIN.UUID"
        - "swissNAMES3D_LIN.OBJEKTART"
        - "swissNAMES3D_LIN.OBJEKTKLAS"
        - "swissNAMES3D_LIN.KUNSTBAUTE"
        - "swissNAMES3D_LIN.NAME_UUID"
        - "swissNAMES3D_LIN.NAME"
        - "swissNAMES3D_LIN.STATUS"
        - "swissNAMES3D_LIN.SPRACHCODE"
        - "swissNAMES3D_LIN.NAMEN_TYP"
        - "swissNAMES3D_LIN.NAMENGRUPP"
        - "swissNAMES3D_LIN.geometry"
        - "swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.NAME AS GEMEINDE_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.BFS_NUMMER AS GEMEINDE_BFS_NUMMER"
        - "swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.NAME AS BEZIRK_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.BEZIRKSNUM AS BEZIRKSNUM"
        - "swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.NAME AS KANTON_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.KANTONSNUM AS KANTONSNUM"
      from:
        - swissNAMES3D_LIN
      join:
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET ON ST_Within(ST_Centroid(swissNAMES3D_LIN.geometry), swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.geometry)"
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET ON swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.BEZIRKSNUM = swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.BEZIRKSNUM"
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET ON swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.KANTONSNUM = swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.KANTONSNUM"

  - name: swissNAMES3D_PLY_enriched
    statement:
      select:
        - "swissNAMES3D_PLY.UUID"
        - "swissNAMES3D_PLY.OBJEKTART"
        - "swissNAMES3D_PLY.OBJEKTKLAS"
        - "swissNAMES3D_PLY.EINWOHNERK"
        - "swissNAMES3D_PLY.NAME_UUID"
        - "swissNAMES3D_PLY.NAME"
        - "swissNAMES3D_PLY.STATUS"
        - "swissNAMES3D_PLY.SPRACHCODE"
        - "swissNAMES3D_PLY.NAMEN_TYP"
        - "swissNAMES3D_PLY.NAMENGRUPP"
        - "swissNAMES3D_PLY.ISCED"
        - "swissNAMES3D_PLY.geometry"
        - "swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.NAME AS GEMEINDE_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.BFS_NUMMER AS GEMEINDE_BFS_NUMMER"
        - "swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.NAME AS BEZIRK_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.BEZIRKSNUM AS BEZIRKSNUM"
        - "swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.NAME AS KANTON_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.KANTONSNUM AS KANTONSNUM"
      from:
        - swissNAMES3D_PLY
      join:
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET ON ST_Within(ST_Centroid(swissNAMES3D_PLY.geometry), swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.geometry)"
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET ON swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.BEZIRKSNUM = swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.BEZIRKSNUM"
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET ON swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.KANTONSNUM = swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.KANTONSNUM"

  - name: swissBOUNDARIES3D_HOHEITSGEBIET_enriched
    statement:
      select:
        - "swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.*"
        - "swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.NAME AS BEZIRK_NAME"
        - "swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.NAME AS KANTON_NAME"
      from:
        - swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET
      join:
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET ON swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.BEZIRKSNUM = swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.BEZIRKSNUM"
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET ON swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.KANTONSNUM = swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.KANTONSNUM"

  - name: swissBOUNDARIES3D_BEZIRKSGEBIET_enriched
    statement:
      select:
        - "swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.*"
        - "swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.NAME AS KANTON_NAME"
      from:
        - swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET
      join:
        - "LEFT JOIN swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET ON swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.KANTONSNUM = swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.KANTONSNUM"

features:
  - table: swissNAMES3D_PKT_enriched
    identifier_column: UUID
  - table: swissNAMES3D_LIN_enriched
    identifier_column: UUID
  - table: swissNAMES3D_PLY_enriched
    identifier_column: UUID
  - table: swissBOUNDARIES3D_HOHEITSGEBIET_enriched
    identifier_column: UUID
  - table: swissBOUNDARIES3D_BEZIRKSGEBIET_enriched
    identifier_column: UUID
  - table: swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET
    identifier_column: UUID

toponyms:
  - table: swissNAMES3D_PKT_enriched
    identifier_column: UUID
    toponym_column: NAME
  - table: swissNAMES3D_LIN_enriched
    identifier_column: UUID
    toponym_column: NAME
  - table: swissNAMES3D_PLY_enriched
    identifier_column: UUID
    toponym_column: NAME
  - table: swissBOUNDARIES3D_HOHEITSGEBIET_enriched
    identifier_column: UUID
    toponym_column: NAME
  - table: swissBOUNDARIES3D_BEZIRKSGEBIET_enriched
    identifier_column: UUID
    toponym_column: NAME
  - table: swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET
    identifier_column: UUID
    toponym_column: NAME