- name: geonames
  location_identifier: geonameid
  data:
  - name: allCountries
    url: https://download.geonames.org/export/dump/allCountries.zip
    extracted_file: allCountries.txt
    columns:
    - name: geonameid
      type: INTEGER
      primary: true
    - name: name
      type: TEXT
    - name: asciiname
      type: TEXT
    - name: alternatenames
      type: TEXT
    - name: latitude
      type: REAL
    - name: longitude
      type: REAL
    - name: feature_class
      type: TEXT
    - name: feature_code
      type: TEXT
    - name: country_code
      type: TEXT
    - name: cc2
      type: TEXT
    - name: admin1_code
      type: TEXT
    - name: admin2_code
      type: TEXT
    - name: admin3_code
      type: TEXT
    - name: admin4_code
      type: TEXT
    - name: population
      type: INTEGER
    - name: elevation
      type: INTEGER
    - name: dem
      type: INTEGER
    - name: timezone
      type: TEXT
    - name: modification_date
      type: TEXT
    toponym_columns:
    - name: name
    - name: alternatenames
      separator: ","
  - name: admin1CodesASCII
    url: https://download.geonames.org/export/dump/admin1CodesASCII.txt
    extracted_file: admin1CodesASCII.txt
    columns:
    - name: admin1_full_code
      type: TEXT
      primary: true
    - name: admin1_name
      type: TEXT
    - name: admin1_asciiname
      type: TEXT
    - name: admin1_geonameid
      type: INTEGER
  - name: admin2Codes
    url: https://download.geonames.org/export/dump/admin2Codes.txt
    extracted_file: admin2Codes.txt
    columns:
    - name: admin2_full_code
      type: TEXT
      primary: true
    - name: admin2_name
      type: TEXT
    - name: admin2_asciiname
      type: TEXT
    - name: admin2_geonameid
      type: INTEGER
  - name: countryInfo
    url: https://download.geonames.org/export/dump/countryInfo.txt
    extracted_file: countryInfo.txt
    columns:
    - name: ISO
      type: TEXT
      primary: true
    - name: ISO3
      type: TEXT
    - name: ISO_Numeric
      type: INTEGER
    - name: fips
      type: TEXT
    - name: country_name
      type: TEXT
    - name: capital
      type: TEXT
    - name: area
      type: REAL
    - name: country_population
      type: INTEGER
    - name: continent
      type: TEXT
    - name: tld
      type: TEXT
    - name: currencyCode
      type: TEXT
    - name: currencyName
      type: TEXT
    - name: Phone
      type: TEXT
    - name: postalCodeFormat
      type: TEXT
    - name: postalCodeRegex
      type: TEXT
    - name: languages
      type: TEXT
    - name: country_geonameid
      type: INTEGER
    - name: neighbours
      type: TEXT
    - name: equivalentFipsCode
      type: TEXT
    skiprows: 50
  - name: featureCodes
    url: https://download.geonames.org/export/dump/featureCodes_en.txt
    extracted_file: featureCodes_en.txt
    columns:
    - name: feature_full_code
      type: TEXT
      primary: true
    - name: feature_name
      type: TEXT
    - name: feature_description
      type: TEXT
