- name: geonames
  location_identifier: geonameid
  location_coordinates:
    x_column: longitude
    y_column: latitude
    crs: EPSG:4326
  location_columns:
  - name: geonameid
    type: TEXT
    primary: true
  - name: name
    type: TEXT
  - name: feature_type
    type: TEXT
  - name: latitude
    type: REAL
  - name: longitude
    type: REAL
  - name: elevation
    type: INTEGER
  - name: population
    type: INTEGER
  - name: admin2_geonameid
    type: TEXT
  - name: admin2_name
    type: TEXT
  - name: admin1_geonameid
    type: TEXT
  - name: admin1_name
    type: TEXT
  - name: country_geonameid
    type: TEXT
  - name: country_name
    type: TEXT
  data:
  - name: allCountries
    url: https://download.geonames.org/export/dump/allCountries.zip
    extracted_files:
    - allCountries.txt
    columns:
    - name: geonameid
      type: TEXT
      primary: true
    - name: name
      type: TEXT
    - name: asciiname
      type: TEXT
    - name: alternatenames
      type: TEXT
    - name: latitude
      type: REAL
    - name: longitude
      type: REAL
    - name: feature_class
      type: TEXT
    - name: feature_code
      type: TEXT
    - name: country_code
      type: TEXT
    - name: cc2
      type: TEXT
    - name: admin1_code
      type: TEXT
    - name: admin2_code
      type: TEXT
    - name: admin3_code
      type: TEXT
    - name: admin4_code
      type: TEXT
    - name: population
      type: INTEGER
    - name: elevation
      type: INTEGER
    - name: dem
      type: INTEGER
    - name: timezone
      type: TEXT
    - name: modification_date
      type: TEXT
    toponym_columns:
    - name: name
    - name: alternatenames
      separator: ","
  - name: admin1CodesASCII
    url: https://download.geonames.org/export/dump/admin1CodesASCII.txt
    extracted_files:
    - admin1CodesASCII.txt
    columns:
    - name: code
      type: TEXT
      primary: true
    - name: name
      type: TEXT
    - name: asciiname
      type: TEXT
    - name: geonameid
      type: TEXT
  - name: admin2Codes
    url: https://download.geonames.org/export/dump/admin2Codes.txt
    extracted_files:
    - admin2Codes.txt
    columns:
    - name: code
      type: TEXT
      primary: true
    - name: name
      type: TEXT
    - name: asciiname
      type: TEXT
    - name: geonameid
      type: TEXT
  - name: countryInfo
    url: https://download.geonames.org/export/dump/countryInfo.txt
    extracted_files:
    - countryInfo.txt
    columns:
    - name: ISO
      type: TEXT
      primary: true
    - name: ISO3
      type: TEXT
    - name: ISO_Numeric
      type: INTEGER
    - name: fips
      type: TEXT
    - name: Country
      type: TEXT
    - name: Capital
      type: TEXT
    - name: Area
      type: REAL
    - name: Population
      type: INTEGER
    - name: Continent
      type: TEXT
    - name: tld
      type: TEXT
    - name: CurrencyCode
      type: TEXT
    - name: CurrencyName
      type: TEXT
    - name: Phone
      type: TEXT
    - name: PostalCodeFormat
      type: TEXT
    - name: PostalCodeRegex
      type: TEXT
    - name: Languages
      type: TEXT
    - name: geonameid
      type: TEXT
    - name: neighbours
      type: TEXT
    - name: EquivalentFipsCode
      type: TEXT
    skiprows: 50
  - name: featureCodes
    url: https://download.geonames.org/export/dump/featureCodes_en.txt
    extracted_files:
    - featureCodes_en.txt
    columns:
    - name: code
      type: TEXT
      primary: true
    - name: name
      type: TEXT
    - name: description
      type: TEXT
- name: swissnames3d
  location_identifier: UUID
  location_coordinates:
    x_column: E
    y_column: N
    crs: EPSG:2056
  location_columns:
  - name: UUID
    type: TEXT
    primary: true
  - name: NAME
    type: TEXT
  - name: OBJEKTART
    type: TEXT
  - name: E
    type: INTEGER
  - name: N
    type: INTEGER
  - name: GEMEINDE_UUID
    type: TEXT
  - name: GEMEINDE_NAME
    type: TEXT
  - name: BEZIRK_UUID
    type: TEXT
  - name: BEZIRK_NAME
    type: TEXT
  - name: KANTON_UUID
    type: TEXT
  - name: KANTON_NAME
    type: TEXT
  data:
  - name: swissNAMES3D_PKT
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    extracted_files:
      - swissNAMES3D_PKT.shp
      - swissNAMES3D_PKT.dbf
      - swissNAMES3D_PKT.shx
      - swissNAMES3D_PKT.prj
      - swissNAMES3D_PKT.cpg
    columns:
    - name: UUID
      type: TEXT
    - name: OBJEKTART
      type: TEXT
    - name: OBJEKTKLAS
      type: TEXT
    - name: HOEHE
      type: REAL
    - name: GEBAEUDENU
      type: TEXT
    - name: NAME_UUID
      type: TEXT
    - name: NAME
      type: TEXT
    - name: STATUS
      type: TEXT
    - name: SPRACHCODE
      type: TEXT
    - name: NAMEN_TYP
      type: TEXT
    - name: NAMENGRUPP
      type: TEXT
    toponym_columns:
    - name: NAME
      geoqualifier_pattern: \s(?:\((?:[A-Z]{2})\)|[A-Z]{2})$
  - name: swissNAMES3D_LIN
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    extracted_files:
      - swissNAMES3D_LIN.shp
      - swissNAMES3D_LIN.dbf
      - swissNAMES3D_LIN.shx
      - swissNAMES3D_LIN.prj
      - swissNAMES3D_LIN.cpg
    columns:
    - name: UUID
      type: TEXT
    - name: OBJEKTART
      type: TEXT
    - name: OBJEKTKLAS
      type: TEXT
    - name: KUNSTBAUTE
      type: TEXT
    - name: NAME_UUID
      type: TEXT
    - name: NAME
      type: TEXT
    - name: STATUS
      type: TEXT
    - name: SPRACHCODE
      type: TEXT
    - name: NAMEN_TYP
      type: TEXT
    - name: NAMENGRUPP
      type: TEXT
    toponym_columns:
    - name: NAME
      geoqualifier_pattern: \s(?:\((?:[A-Z]{2})\)|[A-Z]{2})$
  - name: swissNAMES3D_PLY
    url: https://data.geo.admin.ch/ch.swisstopo.swissnames3d/swissnames3d_2024/swissnames3d_2024_2056.shp.zip
    extracted_files:
      - swissNAMES3D_PLY.shp
      - swissNAMES3D_PLY.dbf
      - swissNAMES3D_PLY.shx
      - swissNAMES3D_PLY.prj
      - swissNAMES3D_PLY.cpg
    columns:
    - name: UUID
      type: TEXT
    - name: OBJEKTART
      type: TEXT
    - name: OBJEKTKLAS
      type: TEXT
    - name: EINWOHNERK
      type: TEXT
    - name: NAME_UUID
      type: TEXT
    - name: NAME
      type: TEXT
    - name: STATUS
      type: TEXT
    - name: SPRACHCODE
      type: TEXT
    - name: NAMEN_TYP
      type: TEXT
    - name: NAMENGRUPP
      type: TEXT
    - name: ISCED
      type: TEXT
    toponym_columns:
    - name: NAME
      geoqualifier_pattern: \s(?:\((?:[A-Z]{2})\)|[A-Z]{2})$
  - name: swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    extracted_files:
      - swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.shp
      - swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.dbf
      - swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.shx
      - swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.prj
      - swissBOUNDARIES3D_1_5_TLM_HOHEITSGEBIET.cpg
    columns:
      - name: UUID
        type: TEXT
        primary: true
      - name: DATUM_AEND
        type: DATE
      - name: DATUM_ERST
        type: DATE
      - name: ERSTELL_J
        type: INTEGER
      - name: ERSTELL_M
        type: TEXT
      - name: GRUND_AEND
        type: TEXT
      - name: HERKUNFT
        type: TEXT
      - name: HERKUNFT_J
        type: INTEGER
      - name: HERKUNFT_M
        type: TEXT
      - name: REVISION_J
        type: INTEGER
      - name: REVISION_M
        type: TEXT
      - name: REVISION_Q
        type: TEXT
      - name: OBJEKTART
        type: TEXT
      - name: BFS_NUMMER
        type: INTEGER
      - name: BEZIRKSNUM
        type: INTEGER
      - name: KANTONSNUM
        type: INTEGER
      - name: NAME
        type: TEXT
      - name: GEM_FLAECH
        type: REAL
      - name: SEE_FLAECH
        type: REAL
      - name: ICC
        type: TEXT
      - name: SHN
        type: TEXT
      - name: EINWOHNERZ
        type: INTEGER
      - name: HIST_NR
        type: INTEGER
    toponym_columns:
      - name: NAME
        geoqualifier_pattern: \s(?:\((?:[A-Z]{2})\)|[A-Z]{2})$
  - name: swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    extracted_files:
      - swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.shp
      - swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.dbf
      - swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.shx
      - swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.prj
      - swissBOUNDARIES3D_1_5_TLM_BEZIRKSGEBIET.cpg
    columns:
      - name: UUID
        type: TEXT
        primary: true
      - name: DATUM_AEND
        type: DATE
      - name: DATUM_ERST
        type: DATE
      - name: ERSTELL_J
        type: INTEGER
      - name: ERSTELL_M
        type: TEXT
      - name: GRUND_AEND
        type: TEXT
      - name: HERKUNFT
        type: TEXT
      - name: HERKUNFT_J
        type: INTEGER
      - name: HERKUNFT_M
        type: TEXT
      - name: REVISION_J
        type: INTEGER
      - name: REVISION_M
        type: TEXT
      - name: REVISION_Q
        type: TEXT
      - name: OBJEKTART
        type: TEXT
      - name: BEZIRKSNUM
        type: INTEGER
      - name: SEE_FLAECH
        type: REAL
      - name: BEZIRKSFLA
        type: REAL
      - name: NAME
        type: TEXT
      - name: KANTONSNUM
        type: INTEGER
      - name: ICC
        type: TEXT
      - name: EINWOHNERZ
        type: INTEGER
    toponym_columns:
    - name: NAME
      geoqualifier_pattern: \s(?:\((?:[A-Z]{2})\)|[A-Z]{2})$
  - name: swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET
    url: https://data.geo.admin.ch/ch.swisstopo.swissboundaries3d/swissboundaries3d_2024-01/swissboundaries3d_2024-01_2056_5728.shp.zip
    extracted_files:
      - swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.shp
      - swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.dbf
      - swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.shx
      - swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.prj
      - swissBOUNDARIES3D_1_5_TLM_KANTONSGEBIET.cpg
    columns:
      - name: UUID
        type: TEXT
        primary: true
      - name: DATUM_AEND
        type: DATE
      - name: DATUM_ERST
        type: DATE
      - name: ERSTELL_J
        type: INTEGER
      - name: ERSTELL_M
        type: TEXT
      - name: GRUND_AEND
        type: TEXT
      - name: HERKUNFT
        type: TEXT
      - name: HERKUNFT_J
        type: INTEGER
      - name: HERKUNFT_M
        type: TEXT
      - name: REVISION_J
        type: INTEGER
      - name: REVISION_M
        type: TEXT
      - name: REVISION_Q
        type: TEXT
      - name: OBJEKTART
        type: TEXT
      - name: KANTONSNUM
        type: INTEGER
      - name: SEE_FLAECH
        type: REAL
      - name: KANTONSFLA
        type: REAL
      - name: NAME
        type: TEXT
      - name: ICC
        type: TEXT
      - name: EINWOHNERZ
        type: INTEGER
    toponym_columns:
    - name: NAME
      geoqualifier_pattern: \s(?:\((?:[A-Z]{2})\)|[A-Z]{2})$
