name: integration-tests

on:
  push:
    branches:
      - development
      - staging
      - main


jobs:
  gazetteer:
    strategy:
      matrix:
        gazetteer: [geonames, swissnames3d]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
      - name: Setup local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Install project dependencies
        run: poetry install
      - name: Download gazetteer
        run: poetry run python -m geoparser download ${{ matrix.gazetteer }}
      - name: Run E2E-script
        run: poetry run python ./tests/integration/e2e.py ${{ matrix.gazetteer }}
